### ISSUE TITLE
Virustotal marks file as malicious from 3 vendors

### ISSUE THREAD

**Issue by jackbuilder52** [LilShieru/DAWRPC#1]
https://www.virustotal.com/gui/file/31284a68968341ea6a9e4588e2e1a6d96faefb090e465f320ef553d42ba03483/detection

your virustotal scan of the zip was green. mine is a different story.
https://www.virustotal.com/gui/file/56a83cc95ef2fc84d485b39b13c44fab2b5e3f93f9b588fbad6fce89de3e9035/details

**Comment by LilShieru** [comment]
I don't know why my repository is marked as a virus from 3 vendors, and I have no idea how to fix it, but there was nothing harmful in my application.
If you don't believe, just review the source code and build it from that source.
