### ISSUE TITLE
It's didn't work in reaper

### ISSUE THREAD

**Issue by YuuJinS** [LilShieru/DAWRPC#2]
Discord Version: October 4, 2021
DAWRPC Version: v1.4
Reaper Version: v6.38
OS: Windows 11 21H2 1000.22000.258.0
![image](https://user-images.githubusercontent.com/34113239/139110133-98b5aee9-5f78-40b4-920b-d47bebaea9cf.png)

**Comment by LilShieru** [comment]
Oops, I just remembered that my older Discord account holding the presence applications is gone so there's no Presence while running this application but I forgot to fix it.
I have already known the problem and are going to fix it. Thank you for reporting.

**Comment by LilShieru** [comment]
The problem has been finally fixed on version 1.4.1.
Sorry for keeping you waiting so long.
