### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by rauldipeas** [LilShieru/DAWRPC#3]
Any chances to get it running on Linux?

**Comment by LilShieru** [comment]
No, since the application uses Windows' API and cannot work properly on Linux, **even with the Wine application.**
Sorry about that.

**Comment by dxcvvxd** [comment]
> No, since the application uses Windows' API and cannot work properly on Linux, **even with the Wine application.** Sorry about that.

any way to make it not use the windows api?

**Comment by Serena1432** [comment]
> any way to make it not use the windows api?

I will do it on my new project soon! Just be patient 👌🏻
